services:
  # Frontend Service (Static Site)
  - type: web
    name: panduranga-traders-frontend
    env: static
    buildCommand: |
      npm install
      cd office_bills && npm install
      npm run build
    staticPublishPath: "./office_bills/dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
  
  # Backend Service (Node.js) - Free Tier
  - type: web
    name: panduranga-traders-backend
    env: node
    plan: free  # Free tier
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    numInstances: 1
