databases:
  - name: panduranga-traders-db
    databaseName: panduranga_traders
    user: panduranga_user
    plan: free

services:
  - type: web
    name: panduranga-traders-frontend
    env: static
    buildCommand: |
      npm install
      cd office_bills && npm install
      npm run build
    staticPublishPath: "./office_bills/dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
