databases:
  - name: panduranga-traders-db
    databaseName: panduranga_traders
    user: panduranga_user
    plan: free

services:
  - type: web
    name: panduranga-traders-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: panduranga-traders-db
          property: connectionString
      - key: PORT
        value: 10000
    numInstances: 1
